#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load user configuration (must define BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

REPO="https://github.com/gingeradditive/gingerDryer"
DEPS=(git python3-pip)

########################################
# Install dependencies                 #
########################################

apt-get install --yes "${DEPS[@]}"


########################################
# Save current dir and switch to home  #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

echo "Cloning gingerDryer repository..."
sudo -u "${BASE_USER}" git clone "${REPO}" gingerDryer

########################################
# Run installation script              #
########################################

echo "Running install script..."
pushd "gingerDryer" &> /dev/null || exit 1

# TODO: enable after fixing 
# sudo -u "${BASE_USER}" bash scripts/install.sh

popd &> /dev/null || exit 1

########################################
# Return to original directory         #
########################################

popd &> /dev/null || exit 1
